export const CODE_MAP: Record<string,string> = {
  "veermata-jijabai-technological-institute-vjti-matunga-mumbai": "03012",
  "veermata jijabai technological institute vjti matunga mumbai": "03012",
  "coep-technological-university": "16006",
  "coep technological university": "16006",
  "institute-of-chemical-technology-matunga-mumbai": "03036",
  "institute of chemical technology matunga mumbai": "03036",
  "bhartiya-vidya-bhavan-s-sardar-patel-institute-of-technology-andheri-mumbai": "03215",
  "bhartiya vidya bhavan s sardar patel institute of technology andheri mumbai": "03215",
  "pune-institute-of-computer-technology": "06271",
  "pune institute of computer technology": "06271",
  "walchand-college-of-engineering-sangli": "06007",
  "walchand college of engineering sangli": "06007",
  "mksss-s-cummins-college-of-engineering-for-women-karvenagar-pune": "06276",
  "mksss s cummins college of engineering for women karvenagar pune": "06276",
  "bansilal-ramnath-agarawal-charitable-trust-s-vishwakarma-institute-of-technology": "06273",
  "bansilal ramnath agarawal charitable trust s vishwakarma institute of technology bibwewadi pune": "06273",
  "sardar-patel-college-of-engineering-andheri": "03014",
  "sardar patel college of engineering andheri": "03014",
  "shri-vile-parle-kelvani-mandal-s-dwarkadas-j-sanghvi-college-of-engineering-vile": "03199",
  "shri vile parle kelvani mandal s dwarkadas j sanghvi college of engineering vile parle mumbai": "03199",
  "pimpri-chinchwad-education-trust-pimpri-chinchwad-college-of-engineering-pune": "06175",
  "pimpri chinchwad education trust pimpri chinchwad college of engineering pune": "06175",
  "thadomal-shahani-engineering-college-bandra-mumbai": "03182",
  "thadomal shahani engineering college bandra mumbai": "03182",
  "vivekanand-education-society-s-institute-of-technology-chembur-mumbai": "03185",
  "vivekanand education society s institute of technology chembur mumbai": "03185",
  "laxminarayan-innovation-technological-university-nagpur": "14005",
  "laxminarayan innovation technological university nagpur": "14005",
  "government-college-of-engineering-chhatrapati-sambhajinagar": "02008",
  "government college of engineering chhatrapati sambhajinagar": "02008",
  "government-college-of-engineering-amravati": "01002",
  "government college of engineering amravati": "01002",
  "dr-d-y-patil-unitech-society-s-dr-d-y-patil-institute-of-technology-pimpri-pune": "06207",
  "dr d y patil unitech society s dr d y patil institute of technology pimpri pune": "06207",
  "shri-guru-gobind-singhji-institute-of-engineering-and-technology-nanded": "02020",
  "shri guru gobind singhji institute of engineering and technology nanded": "02020",
  "pvg-s-college-of-engineering-technology-management": "06274",
  "pvg s college of engineering technology management": "06274",
  "dr-d-y-patil-pratishthan-s-d-y-patil-college-of-engineering-akurdi-pune": "06272",
  "dr d y patil pratishthan s d y patil college of engineering akurdi pune": "06272",
  "fr-conceicao-rodrigues-college-of-engineering-bandra-mumbai": "03184",
  "fr conceicao rodrigues college of engineering bandra mumbai": "03184",
  "government-college-of-engineering-karad": "06005",
  "government college of engineering karad": "06005",
  "k-j-somaiya-institute-of-technology": "03209",
  "k j somaiya institute of technology": "03209",
  "vidyalankar-institute-of-technology-wadala-mumbai": "03139",
  "vidyalankar institute of technology wadala mumbai": "03139",
  "all-india-shri-shivaji-memorial-society-s-college-of-engineering-pune": "06278",
  "all india shri shivaji memorial society s college of engineering pune": "06278",
  "pimpri-chinchwad-education-trust-s-pimpri-chinchwad-college-of-engineering-and-r": "06822",
  "pimpri chinchwad education trust s pimpri chinchwad college of engineering and research ravet": "06822",
  "international-institute-of-information-technology-i-it-pune": "06754",
  "international institute of information technology i it pune": "06754",
  "jaywant-shikshan-prasarak-mandal-s-rajarshi-shahu-college-of-engineering-tathawa": "06141",
  "jaywant shikshan prasarak mandal s rajarshi shahu college of engineering tathawade pune": "06141",
  "all-india-shri-shivaji-memorial-society-s-institute-of-information-technology-pu": "06282",
  "all india shri shivaji memorial society s institute of information technology pune": "06282",
  "thakur-college-of-engineering-and-technology-kandivali-mumbai": "03176",
  "thakur college of engineering and technology kandivali mumbai": "03176",
  "government-college-of-engineering-research-avasari-khurd": "06004",
  "government college of engineering research avasari khurd": "06004",
  "mit-academy-of-engineering-alandi-pune": "06146",
  "mit academy of engineering alandi pune": "06146",
  "k-k-wagh-institute-of-engineering-education-and-research-nashik": "05121",
  "k k wagh institute of engineering education and research nashik": "05121",
  "kolhapur-institute-of-technology-s-college-of-engineering-autonomous-kolhapur": "06267",
  "kolhapur institute of technology s college of engineering autonomous kolhapur": "06267",
  "marathwada-mitra-mandal-s-college-of-engineering-karvenagar-pune": "06156",
  "marathwada mitra mandal s college of engineering karvenagar pune": "06156",
  "s-i-e-s-graduate-school-of-technology-nerul-navi-mumbai": "03211",
  "s i e s graduate school of technology nerul navi mumbai": "03211",
  "don-bosco-institute-of-technology-mumbai": "03208",
  "don bosco institute of technology mumbai": "03208",
  "progressive-education-society-s-modern-college-of-engineering-pune": "06139",
  "progressive education society s modern college of engineering pune": "06139",
  "yeshwantrao-chavan-college-of-engineering-wanadongri-nagpur": "04167",
  "yeshwantrao chavan college of engineering wanadongri nagpur": "04167",
  "xavier-institute-of-engineering-c-o-xavier-technical-institute-mahim-mumbai": "03214",
  "xavier institute of engineering c o xavier technical institute mahim mumbai": "03214",
  "sinhgad-college-of-engineering-vadgaon-bk-pune": "06177",
  "sinhgad college of engineering vadgaon bk pune": "06177",
  "modern-education-society-s-wadia-college-of-engineering-pune": "06281",
  "modern education society s wadia college of engineering pune": "06281",
  "jspm-s-jaywantrao-sawant-college-of-engineering-pune": "06145",
  "jspm s jaywantrao sawant college of engineering pune": "06145",
  "manjara-charitable-trust-s-rajiv-gandhi-institute-of-technology-mumbai": "03135",
  "manjara charitable trust s rajiv gandhi institute of technology mumbai": "03135",
  "sanjivani-rural-education-society-s-sanjivani-college-of-engineering-kopargaon": "05160",
  "sanjivani rural education society s sanjivani college of engineering kopargaon": "05160",
  "k-e-society-s-rajarambapu-institute-of-technology-walwa-sangli": "06214",
  "k e society s rajarambapu institute of technology walwa sangli": "06214",
  "pvgcoe-shrikrushna-s-dhamankar-institute-of-management-nashik": "05330",
  "pvgcoe shrikrushna s dhamankar institute of management nashik": "05330",
  "usha-mittal-institute-of-technology-sndt-women-s-university-mumbai": "03035",
  "usha mittal institute of technology sndt women s university mumbai": "03035",
  "nutan-maharashtra-vidya-prasarak-mandal-nutan-maharashtra-institute-of-engineeri": "06310",
  "nutan maharashtra vidya prasarak mandal nutan maharashtra institute of engineering technology": "06310",
  "vidya-pratishthan-s-kamalnayan-bajaj-institute-of-engineering-technology-baramat": "06284",
  "vidya pratishthan s kamalnayan bajaj institute of engineering technology baramati dist pune": "06284",
  "dattajirao-kadam-technical-education-society-s-textile-engineering-institute-ich": "06222",
  "dattajirao kadam technical education society s textile engineering institute ichalkaranji": "06222",
  "mahatma-education-society-s-pillai-college-of-engineering-new-panvel": "03207",
  "mahatma education society s pillai college of engineering new panvel": "03207",
  "sinhgad-technical-education-society-s-smt-kashibai-navale-college-of-engineering": "06178",
  "sinhgad technical education society s smt kashibai navale college of engineering vadgaon pune": "06178",
  "jspm-narhe-technical-campus": "06755",
  "jspm narhe technical campus": "06755",
  "bharati-vidyapeeth-college-of-engineering-navi-mumbai": "03189",
  "bharati vidyapeeth college of engineering navi mumbai": "03189",
  "jayawant-shikshan-prasarak-mandal-bhivarabai-sawant-institute-of-technology-rese": "06311",
  "jayawant shikshan prasarak mandal bhivarabai sawant institute of technology research wagholi": "06311",
  "marathwada-mitra-mandal-s-institute-of-technology-lohgaon-pune": "06203",
  "marathwada mitra mandal s institute of technology lohgaon pune": "06203",
  "bharati-vidyapeeth-s-college-of-engineering-for-women-katraj-dhankawadi-pune": "06285",
  "bharati vidyapeeth s college of engineering for women katraj dhankawadi pune": "06285",
  "nbn-sinhgad-technical-institutes-campus-pune": "06772",
  "nbn sinhgad technical institutes campus pune": "06772",
  "bharati-vidyapeeth-s-college-of-engineering-lavale-pune": "06796",
  "bharati vidyapeeth s college of engineering lavale pune": "06796",
  "vidya-prasarini-sabha-s-college-of-engineering-technology-lonavala": "06815",
  "vidya prasarini sabha s college of engineering technology lonavala": "06815",
  "government-college-of-engineering-kolhapur": "06036",
  "government college of engineering kolhapur": "06036",
  "ajeenkya-dy-patil-school-of-engineering-lohegaon-pune": "06732",
  "ajeenkya dy patil school of engineering lohegaon pune": "06732",
  "g-h-raisoni-college-of-engineering-management-wagholi-pune": "06155",
  "g h raisoni college of engineering management wagholi pune": "06155",
  "walchand-institute-of-technology-solapur": "06265",
  "walchand institute of technology solapur": "06265",
  "indira-college-of-engineering-management-pune": "06179",
  "indira college of engineering management pune": "06179",
  "sinhgad-technical-education-society-sinhgad-institute-of-technology-and-science-": "06182",
  "sinhgad technical education society sinhgad institute of technology and science narhe ambegaon": "06182",
  "amrutvahini-sheti-shikshan-vikas-sanstha-s-amrutvahini-college-of-engineering-sa": "05162",
  "amrutvahini sheti shikshan vikas sanstha s amrutvahini college of engineering sangamner": "05162",
  "deogiri-institute-of-engineering-and-management-studies-aurangabad": "02114",
  "deogiri institute of engineering and management studies aurangabad": "02114",
  "tssms-s-pd-vasantdada-patil-institute-of-technology-bavdhan-pune": "06122",
  "tssms s pd vasantdada patil institute of technology bavdhan pune": "06122",
  "ankush-shikshan-sanstha-s-g-h-raisoni-college-of-engineering-nagpur": "04116",
  "ankush shikshan sanstha s g h raisoni college of engineering nagpur": "04116",
  "svkm-s-shri-bhagubhai-mafatlal-polytechnic-college-of-engineering": "03025",
  "svkm s shri bhagubhai mafatlal polytechnic college of engineering": "03025",
  "maratha-vidya-prasarak-samaj-s-karmaveer-adv-baburao-ganpatrao-thakare-college-o": "05108",
  "maratha vidya prasarak samaj s karmaveer adv baburao ganpatrao thakare college of engineering nashik": "05108",
  "terna-engineering-college-nerul-navi-mumbai": "03190",
  "terna engineering college nerul navi mumbai": "03190",
  "puranmal-lahoti-government-institute-of-engineering-and-technology-latur": "02015",
  "puranmal lahoti government institute of engineering and technology latur": "02015",
  "sinhgad-academy-of-engineering-kondhwa-bk-kondhwa-saswad-road-pune": "06187",
  "sinhgad academy of engineering kondhwa bk kondhwa saswad road pune": "06187",
  "sinhgad-institute-of-technology": "06185",
  "sinhgad institute of technology": "06185",
  "rasiklal-m-dhariwal-sinhgad-technical-institutes-campus-warje-pune": "06769",
  "rasiklal m dhariwal sinhgad technical institutes campus warje pune": "06769",
  "anantrao-pawar-college-of-engineering-research-pune": "06794",
  "anantrao pawar college of engineering research pune": "06794",
  "met-bhujbal-knowledge-city-met-league-s-engineering-college-adgaon-nashik": "05151",
  "met bhujbal knowledge city met league s engineering college adgaon nashik": "05151",
  "zeal-education-society-s-zeal-college-of-engineering-reserch-narhe-pune": "06298",
  "zeal education society s zeal college of engineering reserch narhe pune": "06298",
  "isbm-college-of-engineering-pune": "06622",
  "isbm college of engineering pune": "06622",
  "dr-d-y-patil-technical-campus-varale-talegaon-pune": "06991",
  "dr d y patil technical campus varale talegaon pune": "06991",
  "government-college-of-engineering-nagpur": "04025",
  "government college of engineering nagpur": "04025",
  "dhole-patil-education-society-dhole-patil-college-of-engineering-wagholi-tal-hav": "06307",
  "dhole patil education society dhole patil college of engineering wagholi tal haveli": "06307",
  "government-college-of-engineering-jalgaon": "05004",
  "government college of engineering jalgaon": "05004",
  "dr-d-y-patil-college-of-engineering-innovation-talegaon": "06834",
  "dr d y patil college of engineering innovation talegaon": "06834",
  "kjei-s-trinity-academy-of-engineering-yewalewadi-pune": "06634",
  "kjei s trinity academy of engineering yewalewadi pune": "06634",
  "government-college-of-engineering-yavatmal": "01012",
  "government college of engineering yavatmal": "01012",
  "skn-sinhgad-institute-of-technology-science-kusgaon-bk-pune": "06770",
  "skn sinhgad institute of technology science kusgaon bk pune": "06770",
  "genba-sopanrao-moze-trust-parvatibai-genba-moze-college-of-engineering-wagholi-p": "06138",
  "genba sopanrao moze trust parvatibai genba moze college of engineering wagholi pune": "06138",
  "pune-district-education-association-s-college-of-engineering-manjari-bk-hadapsar": "06206",
  "pune district education association s college of engineering manjari bk hadapsar pune": "06206",
  "annasaheb-dange-college-of-engineering-and-technology-ashta-sangli": "06283",
  "annasaheb dange college of engineering and technology ashta sangli": "06283",
  "sanjay-ghodawat-institute": "06811",
  "sanjay ghodawat institute": "06811",
  "government-college-of-engineering-chandrapur": "04004",
  "government college of engineering chandrapur": "04004",
  "alard-charitable-trust-s-alard-college-of-engineering-and-management-pune": "06325",
  "alard charitable trust s alard college of engineering and management pune": "06325",
  "lokmanya-tilak-jankalyan-shikshan-sanstha-priyadarshani-college-of-engineering-n": "04123",
  "lokmanya tilak jankalyan shikshan sanstha priyadarshani college of engineering nagpur": "04123",
  "genba-sopanrao-moze-college-of-engineering-baner-balewadi-pune": "06144",
  "genba sopanrao moze college of engineering baner balewadi pune": "06144",
  "m-g-m-s-college-of-engineering-and-technology-kamothe-navi-mumbai": "03175",
  "m g m s college of engineering and technology kamothe navi mumbai": "03175",
  "k-j-s-educational-institut-trinity-college-of-engineering-and-research-pisoli-ha": "06184",
  "k j s educational institut trinity college of engineering and research pisoli haveli": "06184",
  "gokhale-education-society-s-r-h-sapat-college-of-engineering-management-studies-": "05181",
  "gokhale education society s r h sapat college of engineering management studies and research nashik": "05181",
  "tssm-s-bhivarabai-sawant-college-of-engineering-and-research-narhe-pune": "06649",
  "tssm s bhivarabai sawant college of engineering and research narhe pune": "06649",
  "sveri-s-college-of-engineering-pandharpur": "06220",
  "sveri s college of engineering pandharpur": "06220",
  "s-k-n-sinhgad-college-of-engineering-korti-tal-pandharpur-dist-solapur": "06643",
  "s k n sinhgad college of engineering korti tal pandharpur dist solapur": "06643",
  "pravara-rural-college-of-engineering-loni-pravaranagar-ahmednagar": "05139",
  "pravara rural college of engineering loni pravaranagar ahmednagar": "05139",
  "csmss-chh-shahu-college-of-engineering-aurangabad": "02533",
  "csmss chh shahu college of engineering aurangabad": "02533",
  "loknete-shamrao-peje-government-college-of-engineering-ratnagiri": "03042",
  "loknete shamrao peje government college of engineering ratnagiri": "03042",
  "pradnya-niketan-education-society-s-nagesh-karajagi-orchid-college-of-engineerin": "06223",
  "pradnya niketan education society s nagesh karajagi orchid college of engineering technology solapur": "06223",
  "mahatma-gandhi-missions-college-of-engineering-hingoli-rd-nanded": "02127",
  "mahatma gandhi missions college of engineering hingoli rd nanded": "02127",
  "dr-vithalrao-vikhe-patil-college-of-engineering-ahmednagar": "05161",
  "dr vithalrao vikhe patil college of engineering ahmednagar": "05161",
  "p-k-technical-campus-pune": "06768",
  "p k technical campus pune": "06768",
  "shree-ramchandra-college-of-engineering-lonikand-pune": "06759",
  "shree ramchandra college of engineering lonikand pune": "06759",
  "keystone-school-of-engineering-pune": "06808",
  "keystone school of engineering pune": "06808",
  "tatyasaheb-kore-institute-of-engineering-and-technology-warananagar": "06268",
  "tatyasaheb kore institute of engineering and technology warananagar": "06268",
  "g-s-mandal-s-maharashtra-institute-of-technology-aurangabad": "02113",
  "g s mandal s maharashtra institute of technology aurangabad": "02113",
  "sandip-foundation-sandip-institute-of-technology-and-research-centre-mahiravani-": "05109",
  "sandip foundation sandip institute of technology and research centre mahiravani nashik": "05109",
  "navsahyadri-education-society-s-group-of-institutions": "06632",
  "navsahyadri education society s group of institutions": "06632",
  "dr-d-y-patil-pratishthan-s-college-of-engineering-kolhapur": "06839",
  "dr d y patil pratishthan s college of engineering kolhapur": "06839",
  "snjb-s-late-sau-kantabai-bhavarlalji-jain-college-of-engineering-jain-gurukul-ne": "05173",
  "snjb s late sau kantabai bhavarlalji jain college of engineering jain gurukul neminagar chandwad nashik": "05173",
  "d-y-patil-college-of-engineering-and-technology-kolhapur": "06250",
  "d y patil college of engineering and technology kolhapur": "06250",
  "rajgad-technical-campus": "06324",
  "rajgad technical campus": "06324",
  "d-y-patil-education-society-s-d-y-patil-technical-campus-faculty-of-engineering-": "06780",
  "d y patil education society s d y patil technical campus faculty of engineering faculty of management talsande kolhapur": "06780",
  "peoples-education-society-s-college-of-engineering-aurangabad": "02134",
  "peoples education society s college of engineering aurangabad": "02134",
  "suman-ramesh-tulsiani-technical-campus-faculty-of-engineering-kamshet-pune": "06767",
  "suman ramesh tulsiani technical campus faculty of engineering kamshet pune": "06767",
  "shree-siddheshwar-women-s-college-of-engineering-solapur": "06938",
  "shree siddheshwar women s college of engineering solapur": "06938",
  "mes-mukunddas-lohia-college-of-engineering": "16357",
  "mes mukunddas lohia college of engineering": "16357",
  "yashoda-mahadeo-kakade-college-of-engineering-talegaon": "16352",
  "yashoda mahadeo kakade college of engineering talegaon": "16352",
  "bharati-vidyapeeth-s-college-of-engineering-kolhapur": "06288",
  "bharati vidyapeeth s college of engineering kolhapur": "06288",
  "sanjeevan-group-of-institutions": "06315",
  "sanjeevan group of institutions": "06315",
  "cummins-college-of-engineering-for-women-sukhali-gupchup-tal-hingna-hingna-nagpu": "04304",
  "cummins college of engineering for women sukhali gupchup tal hingna hingna nagpur": "04304",
  "dr-babasaheb-ambedkar-technological-university-lonere": "03033",
  "dr babasaheb ambedkar technological university lonere": "03033",
  "m-s-bidve-engineering-college-latur": "02129",
  "m s bidve engineering college latur": "02129"
};
